---
- include: ../provision.yml

- name: Create Distribution-Version groups
  hosts: all:!localhost
  tasks:
    - group_by: key={{ ansible_distribution }}-{{ ansible_distribution_version|int }}

- name: Prepare for Foreman install
  hosts: foreman_installer
  sudo: yes
  roles:
    - { role: common }
    - { role: linux-common }
    - { role: foreman/common }
  tags:
    - prep

- name: Prepare foreman network
  hosts: foreman_installer
  sudo: yes
  roles:
    - { role: foreman/network-setup }
  tags:
    - prep

- name: Setup tempest networking
  hosts: tempest
  roles:
    - { role: foreman/network-setup, net_interfaces: [ { interface: 'eth1', ip_var: 'tempest_private_ip', ansible_var: 'ansible_eth1' }, { interface: 'eth2', ip_var: 'tempest_public_ip', ansible_var: 'ansible_eth2'} ] }
  tags:
    - tempest_setup

- name: Prepare foreman network - Networker nodes
  hosts: networker
  sudo: yes
  roles:
    - { role: networker }
  tags:
    - prep

# apply pre-packstack workarouds
- include: ../../workarounds/icehouse/workarounds-prep.yml tags=workaround

- name: Install Foreman
  hosts: foreman
  gather_facts: True
  sudo: yes
  roles:
    - { role: foreman/openstack-installer }
    - { role: foreman/hostgroup-params }
  tags:
    - install

- include: ../../workarounds/icehouse/workarounds-pre-run-foreman.yml tags=workaround

- name: Install Controller node
  hosts: controller
  gather_facts: True
  sudo: yes
  roles:
    - { role: foreman/openstack-node-common }
    - { role: foreman/openstack-node }
  tags:
    - install_nodes

- name: Install remaining OpenStack nodes
  hosts: foreman_node:!controller
  gather_facts: True
  sudo: yes
  roles:
    - { role: foreman/openstack-node-common }
    - { role: foreman/openstack-node }
  tags:
    - install_nodes

- include: ../../workarounds/icehouse/workarounds-post-run-foreman.yml tags=workaround

- name: Create Keystone RC files
  hosts: foreman_node
  sudo: yes
  roles:
    - { role: openstack/create-keystonerc }
  tags:
    - keystonerc

- include: ../tempest.yml
