---
#RHEL
- name: Remove yum-rhn-plugin
  yum: name=yum-rhn-plugin state=absent
  register: result

- name: Yum clean all
  command: yum clean all
  when: result|changed

- name: Ensure redhat-release-server
  yum: name=redhat-release-server state=present

- name: Remove all yum repositories
  file: path=/etc/yum.repos.d/{{ item }} state=absent
  with_items: repos_to_remove
  notify:
    - Yum clean all

- name: Create the RHEL Repositories
  template: src=rhel.repo.j2 dest=/etc/yum.repos.d/rhel.repo
  notify:
    - Yum clean all
    - yum -y update to latest packages

- name: Create the EPEL Repository
  template: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo
  notify:
    - Yum clean all
    - yum -y update to latest packages

- name: install httplib2
  yum: name=http://download.devel.redhat.com/brewroot/packages/python-httplib2/0.6.0/6.el7/noarch/python-httplib2-0.6.0-6.el7.noarch.rpm
  when: ansible_distribution == "RedHat" and ansible_distribution_version == "7.0"

- name: Ensure httplib2
  yum: name=python-httplib2 state=present
  when: not (ansible_distribution == "RedHat" and ansible_distribution_version == "7.0")

#WORKAROUND
- name: Ensure /etc/sysconfig/iptables-services
  copy: src=iptables dest=/etc/sysconfig/iptables owner=root group=root mode=0600 force=no

- name: Ensure iptables
  yum: name=iptables state=present

