---
- debug: var=nodes_created
  when: "'debug' in config.verbosity"
- debug: var=floating_ips
  when: "'debug' in config.verbosity"

- name: Network {{ os_network_type }} == {{ network_expected }} |
        Add hosts
  add_host:
      name="{{ item.0.item.name }}"
      groups="{{ item.0.item.groups }}"
      ansible_ssh_host="{{ item.1.public_ip }}"
      ansible_ssh_private_key_file="{{ ssh_private_key }}"
      ansible_ssh_user="{{ item.0.item.remote_user }}"
      public_ip="{{ item.1.public_ip }}"
      private_ip="{{ item.0.private_ip }}"
      ansible_fqdn="{{ item.0.item.hostname }}"
      priv_hostname="{{ item.0.item.hostname }}"
      {{ lookup('template', 'addl_vars.j2') }}
  with_together:
    - nodes_created
    - floating_ips

